### PR TITLE
Set tls verify handler to NULL intially.

### PR DESCRIPTION
**Pull request by mollidor**

### CODE REVIEW

**Comment by felixLam** [comment]
Not sure what the motivation is, but "code wise" this looks good.

**Comment by mollidor** [comment]
Mr @schneider-iosphere should know if he missed this by accident or on purpose. Just noticed it was missing when adding a handler on_state_change.

**Comment by schneider-iosphere** [comment]
Does not matter at all because of Line 145. I honestly don't know why the original maintainer explicitly set everything to NULL. I discovered another issue while reading this. I'll fix it and open a new pull request, ok?

**Comment by mollidor** [comment]
yip

**Pull request closed without merging**
